version: "3"
services:
  tf-models:
    build:
      context: ./tf-models
    image: eu.gcr.io/machinelearning-prod/tf-models:latest
    container_name: model
    environment:
      - MODEL_NAME=${MODEL_NAME}
    ports:
      - "8500:8500"
      - "8501:8501"

  api:
    build:
      context: ./api
    image: eu.gcr.io/machinelearning-prod/session_recommendation:latest
    container_name: api
    environment:
      - MODEL_NAME=${MODEL_NAME}
      - DATASET_NAME=${DATASET}
    ports:
      - "5000:5000"
