apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-recommendation
  namespace: session-recommendation
  labels:
    app: session-recommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: session-recommendation
  template:
    metadata:
      labels:
        app: session-recommendation
    spec:
      tolerations:
      - key: "machine-type"
        operator: "Equal"
        value: "highmem"
        effect: "NoSchedule"
      containers:
        # [START tf-models]
        - name: tf-models
          imagePullPolicy: Always
          image: eu.gcr.io/machinelearning-prod/tf-models:latest
          env:
            - name: MODEL_NAME
              value: only_session_embedding
          ports:
            - protocol: TCP
              containerPort: 8501
        # [END tf-models]
        # [START session-recommendation]
        - name: session-recommendation
          imagePullPolicy: Always
          image: eu.gcr.io/machinelearning-prod/session_recommendation:latest
          env:
            - name: MODEL_NAME
              value: only_session_embedding
            - name: DATASET
              value: maxi_dataset
          resources:
            requests:
              memory: "7.5Gi"
          ports:
            - protocol: TCP
              containerPort: 5000
          readinessProbe:
            httpGet:
              path: /Readiness
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 30
        # [END dg-ml-models]

---
apiVersion: v1
kind: Service
metadata:
    name: session-recommendation
    namespace: session-recommendation
spec:
  type: NodePort
  selector:
    app: session-recommendation
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
